//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application_Commandes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commentaire
    {
        public int ID { get; set; }
        public Nullable<int> ID_Client { get; set; }
        public string Commentaire1 { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
