//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application_Commandes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApplicationCommandesEntities : DbContext
    {
        public ApplicationCommandesEntities()
            : base("name=ApplicationCommandesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Commande> Commandes { get; set; }
        public virtual DbSet<Commentaire> Commentaires { get; set; }
        public virtual DbSet<Facture> Factures { get; set; }
        public virtual DbSet<Ligne_Commande> Ligne_Commandes { get; set; }
        public virtual DbSet<Paiment> Paiments { get; set; }
        public virtual DbSet<Produit> Produits { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
