//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application_Commandes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facture
    {
        public int ID { get; set; }
        public Nullable<int> ID_Commande { get; set; }
        public string Date { get; set; }
    
        public virtual Commande Commande { get; set; }
    }
}
